ML_NAME           = pfan
ML_SRCDIR         = src/kmodule
ML_DRIVER_SRCDIR  = $(ML_SRCDIR)/module

ML_APP            = pearlfan
ML_APP_SRCDIR     = $(ML_SRCDIR)/app

ML_UDEVRULE       = 99-$(ML_NAME).rules

.PHONY: all install clean distclean

all:
	$(MAKE) $(MFLAGS) -C $(ML_DRIVER_SRCDIR)
	$(MAKE) $(MFLAGS) -C $(ML_APP_SRCDIR)
	mv $(ML_APP_SRCDIR)/$(ML_APP) .

install:
	$(MAKE) $(MFLAGS) -C $(ML_DRIVER_SRCDIR) install
	cp $(ML_SRCDIR)/rules.d/$(ML_UDEVRULE) /etc/udev/rules.d/$(ML_UDEVRULE)
	udevadm control --reload-rules
	insmod $(ML_DRIVER_SRCDIR)/$(ML_NAME).ko

clean:
	$(MAKE) $(MFLAGS) -C $(ML_DRIVER_SRCDIR) clean
	$(MAKE) $(MFLAGS) -C $(ML_APP_SRCDIR) clean
	$(RM) $(ML_APP)

distclean: clean
	$(RM) /etc/udev/rules.d/$(ML_UDEVRULE)
	@rmmod $(ML_NAME)
